import {useMemo,useState} from "react";
import {ArrowRight,BookOpen,Bookmark,ChevronRight,Headphones,Menu,Search,Sparkles,Star,X,LayoutDashboard,Library,List,Settings,Users,BarChart3,Link2,Plus,MoreHorizontal} from "lucide-react";

type Book={id:number;title:string;author:string;cover:string;rating:number;pages:number;genre:string;description:string;curated?:boolean};
const books:Book[]=[
{id:1,title:"The Midnight Library",author:"Matt Haig",cover:"https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",rating:4.2,pages:304,genre:"Fiction",curated:true,description:"A moving story about regret, possibility, and the lives we might have lived."},
{id:2,title:"Meditations",author:"Marcus Aurelius",cover:"https://covers.openlibrary.org/b/isbn/9780141395862-L.jpg",rating:4.3,pages:256,genre:"Philosophy",curated:true,description:"A timeless collection of private reflections on discipline, perspective, and a good life."},
{id:3,title:"The Hobbit",author:"J. R. R. Tolkien",cover:"https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",rating:4.7,pages:310,genre:"Fantasy",curated:true,description:"Bilbo Baggins leaves his comfortable home for an unforgettable adventure."},
{id:4,title:"Atomic Habits",author:"James Clear",cover:"https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",rating:4.6,pages:320,genre:"Self-Improvement",curated:true,description:"A practical framework for building better habits through small, consistent changes."},
{id:5,title:"Pride and Prejudice",author:"Jane Austen",cover:"https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",rating:4.5,pages:279,genre:"Classics",curated:true,description:"A sharp, witty classic about first impressions, family, and love."},
{id:6,title:"The Alchemist",author:"Paulo Coelho",cover:"https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",rating:4.4,pages:208,genre:"Fiction",curated:true,description:"A young shepherd follows a dream and discovers a deeper lesson about purpose."},
{id:7,title:"Man's Search for Meaning",author:"Viktor E. Frankl",cover:"https://covers.openlibrary.org/b/isbn/9780807014271-L.jpg",rating:4.4,pages:184,genre:"Psychology",curated:true,description:"Reflections on finding meaning and inner freedom in the face of suffering."},
{id:8,title:"The Little Prince",author:"Antoine de Saint-Exupéry",cover:"https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",rating:4.5,pages:96,genre:"Classics",curated:true,description:"A deceptively simple tale about friendship, wonder, responsibility, and seeing beyond appearances."}];

const collections=[["Books that change how you think","Philosophy · Psychology"],["The best short books","Under 200 pages"],["Classics worth reading","Timeless favorites"],["Books for a fresh start","Life · Growth · Change"]];

function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><div className="header-inner"><a className="brand" href="/"><span className="brand-mark">B</span><span>Books<span>Heaven</span></span></a><nav className={`main-nav ${open?"open":""}`}><a href="#discover">Discover</a><a href="#collections">Collections</a><a href="#genres">Genres</a><a href="#authors">Authors</a></nav><div className="header-actions"><button className="icon-button"><Search size={19}/></button><a className="outline-button" href="/admin">Admin</a><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div></header>}

function BookCard({book}:{book:Book}){return <article className="book-card"><a className="cover-wrap" href={`/books/${book.id}`}><img src={book.cover} alt={book.title}/><button className="save-button"><Bookmark size={17}/></button></a><div className="book-info"><div className="eyebrow">{book.genre}</div><h3>{book.title}</h3><p className="author">{book.author}</p><div className="rating"><Star size={14} fill="currentColor"/><strong>{book.rating}</strong><span>· {book.pages} pages</span></div></div></article>}

function Home(){const[query,setQuery]=useState("");const results=useMemo(()=>query?books.filter(b=>(b.title+" "+b.author+" "+b.genre).toLowerCase().includes(query.toLowerCase())):[],[query]);return <><Header/><main><section className="hero"><div className="hero-glow"/><div className="hero-content"><div className="kicker"><Sparkles size={15}/> HUMAN-CURATED BOOK DISCOVERY</div><h1>Find a book<br/><em>worth your time.</em></h1><p>Discover thoughtful recommendations, timeless classics, and books selected for the way you want to read.</p><div className="hero-search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search books, authors, topics…"/><button>Search</button></div>{results.length>0&&<div className="search-results">{results.slice(0,5).map(b=><a href={`/books/${b.id}`} key={b.id}><img src={b.cover}/><span><b>{b.title}</b><small>{b.author}</small></span><ArrowRight size={16}/></a>)}</div>}<div className="hero-links"><span>Popular:</span>{["Philosophy","Short books","Classics","Psychology"].map(x=><a href="#" key={x}>{x}</a>)}</div></div><div className="hero-books"><div className="hero-book back"><img src={books[2].cover}/></div><div className="hero-book middle"><img src={books[1].cover}/></div><div className="hero-book front"><img src={books[0].cover}/><span className="floating-note">Curated<br/><b>for you</b></span></div></div></section>
<section className="section intro-grid" id="discover"><div><div className="section-label">START HERE</div><h2>Not sure what to read?</h2></div><div><p className="large-copy">Tell us what you're in the mood for. We'll narrow it down using simple, transparent recommendations — no mysterious algorithms.</p><a className="text-link" href="#discover-tool">What should I read? <ArrowRight size={17}/></a></div></section>
<section className="section" id="collections"><div className="section-head"><div><div className="section-label">EDITOR'S SHELF</div><h2>Curated collections</h2></div><a className="text-link" href="#">View all <ArrowRight size={16}/></a></div><div className="collection-grid">{collections.map((c,i)=><a href="#" className="collection" key={c[0]}><span className="collection-number">0{i+1}</span><div><h3>{c[0]}</h3><p>{c[1]}</p></div><ArrowRight/></a>)}</div></section>
<section className="section paper-section"><div className="section-head"><div><div className="section-label">POPULAR NOW</div><h2>Readers are picking these</h2></div><a className="text-link" href="#">See trending <ArrowRight size={16}/></a></div><div className="book-grid">{books.slice(0,5).map(b=><BookCard key={b.id} book={b}/>)}</div></section>
<section className="section split-feature" id="discover-tool"><div className="feature-copy"><div className="section-label">DISCOVER YOUR NEXT READ</div><h2>One question.<br/><em>One good book.</em></h2><p>Choose a mood and we'll point you toward books that match your interests, preferred length, and reading style.</p><a className="light-button" href="#">Start discovering <ArrowRight size={17}/></a></div><div className="mood-panel"><span>WHAT ARE YOU IN THE MOOD FOR?</span><div className="mood-grid">{["Something thought-provoking","A page-turning adventure","A fresh perspective","A quiet classic"].map(x=><button key={x}>{x}<ChevronRight size={17}/></button>)}</div></div></section>
<section className="section" id="genres"><div className="section-head"><div><div className="section-label">EXPLORE</div><h2>Browse by genre</h2></div></div><div className="genre-list">{["Fiction","Philosophy","Psychology","Fantasy","History","Science","Biography","Classics","Self-Improvement","Mystery","Poetry","Business"].map(g=><a href="#" key={g}>{g}<ArrowRight size={15}/></a>)}</div></section>
<section className="newsletter"><div><div className="section-label">THE BOOKSHEAVEN LETTER</div><h2>Good books, occasionally.</h2><p>A short selection of books worth knowing about. No noise.</p></div><form onSubmit={e=>e.preventDefault()}><input placeholder="Your email address"/><button>Subscribe <ArrowRight size={16}/></button></form></section></main><Footer/></>}

function BookPage(){const b=books[5];return <><Header/><main className="book-page"><div className="breadcrumbs">Home <ChevronRight size={13}/> Books <ChevronRight size={13}/> {b.title}</div><div className="book-hero"><div className="detail-cover"><img src={b.cover}/></div><div className="detail-content"><div className="section-label">CURATED BOOK</div><h1>{b.title}</h1><p className="detail-author">by <b>{b.author}</b></p><div className="rating big"><Star size={17} fill="currentColor"/><strong>{b.rating}</strong><span>reader rating</span></div><p className="detail-desc">{b.description}</p><div className="meta-row"><span>{b.pages} pages</span><span>·</span><span>Fiction</span><span>·</span><span>English</span></div><div className="detail-actions"><button className="dark-button"><Bookmark size={17}/> Add to library</button><button className="outline-button"><Headphones size={17}/> Find audiobook</button><button className="outline-button">Buy on Amazon <ArrowRight size={16}/></button></div></div></div><div className="detail-grid"><section><div className="section-label">WHY THIS BOOK</div><h2>A small book with a big idea.</h2><p className="body-copy">The Alchemist is the kind of story that rewards both a quick first read and a slower return. Its central idea — that paying attention to what matters can change the direction of a life — is simple, but surprisingly durable.</p><p className="body-copy">That's why it remains a useful recommendation when someone wants something hopeful, accessible, and quietly philosophical.</p></section><aside className="side-card"><b>Key information</b><div><span>Genre</span><strong>Fiction</strong></div><div><span>Pages</span><strong>208</strong></div><div><span>Language</span><strong>English</strong></div><div><span>Public domain</span><strong>No</strong></div></aside></div><section className="similar"><div className="section-head"><div><div className="section-label">IF YOU LIKED THIS</div><h2>You may also like</h2></div></div><div className="book-grid">{books.slice(1,5).map(x=><BookCard key={x.id} book={x}/>)}</div></section></main><Footer/></>}

function Admin(){const[tab,setTab]=useState("Books");const tabs=[["Dashboard",LayoutDashboard],["Books",Library],["Curated lists",List],["Traffic",BarChart3],["Link health",Link2],["Authors",Users],["Settings",Settings]] as const;return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand admin-brand" href="/"><span className="brand-mark">B</span><span>Books<span>Heaven</span></span></a><div className="admin-caption">CONTENT STUDIO</div>{tabs.map(([name,Icon])=><button className={tab===name?"active":""} onClick={()=>setTab(name)} key={name}><Icon size={18}/>{name}</button>)}<div className="admin-bottom"><a href="/">← Back to website</a><div className="admin-user"><div className="avatar">A</div><span><b>Admin</b><small>Owner</small></span></div></div></aside><div className="admin-main"><div className="admin-top"><div><div className="section-label">ADMIN / {tab.toUpperCase()}</div><h1>{tab}</h1></div><button className="dark-button"><Plus size={17}/> Add book</button></div>{tab==="Books"?<><div className="stats"><div><span>Total books</span><b>2,481</b><small>+38 this month</small></div><div><span>Curated</span><b>1,204</b><small>48.5% of catalog</small></div><div><span>Long-tail</span><b>1,277</b><small>Cached metadata</small></div><div><span>Views / 30d</span><b>84.2K</b><small>+12.8%</small></div></div><div className="admin-toolbar"><div className="admin-search"><Search size={17}/><input placeholder="Search books…"/></div><button className="filter">Status: All <ChevronRight size={15}/></button><button className="filter">Sort: Traffic <ChevronRight size={15}/></button></div><div className="table-card"><table><thead><tr><th>BOOK</th><th>STATUS</th><th>GENRE</th><th>VIEWS</th><th>UPDATED</th><th></th></tr></thead><tbody>{books.slice(0,7).map((b,i)=><tr key={b.id}><td><div className="table-book"><img src={b.cover}/><span><b>{b.title}</b><small>{b.author}</small></span></div></td><td><span className={`status ${b.curated?"green":"gray"}`}>{b.curated?"Curated":"Cached"}</span></td><td>{b.genre}</td><td>{(12000-i*1234).toLocaleString()}</td><td>{i+1}d ago</td><td><button className="more"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></>:<div className="empty-admin"><Sparkles/><h2>{tab}</h2><p>This section is ready for the next development phase. Part 1 uses local mock data only.</p></div>}</div></div>}

function Footer(){return <footer><div className="footer-main"><div><a className="brand" href="/"><span className="brand-mark">B</span><span>Books<span>Heaven</span></span></a><p>Find books worth your time.</p></div><div className="footer-links"><div><b>Discover</b><a href="#">What should I read?</a><a href="#">Collections</a><a href="#">Genres</a></div><div><b>BooksHeaven</b><a href="#">About</a><a href="#">Contact</a><a href="#">Privacy</a></div></div></div><div className="footer-bottom"><span>© 2026 BooksHeaven</span><span>Human-curated · No AI-generated editorial content</span></div></footer>}

export default function App(){const path=window.location.pathname;if(path.startsWith("/admin"))return <Admin/>;if(path.startsWith("/books/"))return <BookPage/>;return <Home/>}